## Demostracion de que es mas rapido con un *arange* de _Python_

In [2]:
import numpy as np

In [3]:

my_arr = np.arange(1_000_000) # este es mas rapido a la hora de calcular valores 
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


1.24 ms ± 390 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32 ms ± 3.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data *10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

numero de filas y columnas

In [7]:
data.shape

(2, 3)

el tipo de elementos 

In [8]:
data.dtype

dtype('float64')

Creando _ndarray_

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arra1 = np.array(data1)
arra1

array([6. , 7.5, 8. , 0. , 1. ])

Convertir una lista de listas en un array


In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Dimension

In [11]:
arr2.ndim
arr2.shape
type(arr2)

numpy.ndarray

array de ceros 

In [12]:
ceros = np.zeros(10)
ceros
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

array de unos 

In [13]:
unos = np.ones(3)
unos
np.ones((6,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.empty((2, 3, 3)) # el primer valor tendra 2 repersetna la cantida de bloques que tendra , 
                    # el otro valor 3 corresponde a la cantidad de filas que tendras 
                    # el valor 2 del final se corresponde con la cantida de filas anidadas que tendra 

np.empty((2, 3, 9)) # Creo que aqui se ve mejor
# Los valoes que se obtiene son valores basuras 

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

## Tipo de datos

In [15]:
arr1 = np.array([1,2,3],dtype = np.float64)
arr1
arr2 = np.array([3,4,5],dtype = np.int32)
arr2

array([3, 4, 5], dtype=int32)

In [16]:
arr2d = np.array([                              #la diferencia es que aqui hay una sola lista 
                [1,2,3],[4,5,6],[7,8,9]])
# arr2d[0][2]
arr2d[2]
# arr2d.astype(np.int32)

array([7, 8, 9])

## Es diferentes cuando es un narray de varias dimensiones 

In [17]:
arr3d = np.array([                                  # la diferencia es que aqui hay dos listas 
    [[1, 2, 3], [4, 5, 6]],  # 0 Primer bloque
    [[7, 8, 9], [10, 11, 12]] # 1 Segundo bloque
])
arr3d[0,1]

array([4, 5, 6])

### Corte en el array


In [18]:
arr3d[:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

#### Seleccion en el array de 2d 

In [19]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
arr2d[:3, 0]

array([1, 4, 7])

In [21]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [22]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Indexado Buleano


In [23]:
names = np.array([ 'Bob' , ' Joe ', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
names


array(['Bob', ' Joe ', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U5')

In [24]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

# Indexar un array boleano y se ve como selecciona las mismas posiciones

In [25]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [26]:
In [106]: data[names == 'Bob', 1:]

array([[7],
       [0]])

# Para negar en este caso se pueden usar estas dos opciones 

In [27]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [28]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [29]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Para elegir dos de los tres nombres y combinar así varias condiciones  booleanas, utilizamos operadores aritméticos booleanos como & (and) y |  (or):

In [30]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [31]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [44]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [33]:
arr[[4, 3, 0, 6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [34]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [35]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

El comportamiento del indexado sofisticado en este caso es algo distinto  a lo que algunos usuarios podrían haber imaginado (yo mismo incluido),  que es la región rectangular formada por elegir un subconjunto de las filas y  colummas de la matriz. Esta es una forma de conseguir esto:

In [36]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##  Transponer arrays e intercambiar ejes 

In [37]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

calcula el producto interno de  una matriz utilizando numpy.dot:

In [39]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

El operador @ es otra forma de hacer multiplicación de matrices:

In [40]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

### Creacion de codigos seudoaleatorios 

In [42]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.62970907,  0.37511079, -0.36066479,  0.96282438],
       [ 1.61839035, -1.63927014, -0.21374746, -2.10815077],
       [ 0.53908839, -1.02230127, -1.29651576,  1.27683651],
       [ 0.07932674,  0.81159281,  0.97967549,  0.14425271]])